# The beehive example configuration

# The node name in the cluster
name = "node4"

# The RPC address to serve requests
raftAddr = "node4:10001"

# The RPC address to serve requests
rpcAddr = "node4:10002"

maxConcurrencySnapChunks = 16
snapChunkSize = 8

applyWorkerCount = 16
raftMaxWorkers = 16

raftPreVote = true

# Raft tick time interval in ms.
raftTickDuration = 1000

# How many ticks to perform timeout elections.
raftElectionTick = 20

# How many ticks to perform raft headrtbeat.
raftHeartbeatTick = 2

# Check the interval of shard split in seconds.
shardSplitCheckDuration = 5

maxProposalBytes = 16

[prophet]
# The application and prophet RPC address, send heartbeats, alloc id, watch event, etc. required
rpcAddr = "node4:9527"

# Store cluster metedata
storeMetadata = false

# The clusters client address list, required while storeMetadata is false
clusters = [
    "node1:2371",
    "node2:2371",
    "node3:2371"
]