version: '2.1'
services:
  node1:
    image: deepfabric/beevector
    ports:
      - "8081:8080"
    volumes:
      - ./cfg/node1.toml:/etc/node.toml
    command: 
      - --addr=node1:8080
      - --data=/tmp
      - --beehive-cfg=/etc/node.toml
      - --max=1000000
      - --dim=512

  node2:
    image: deepfabric/beevector
    ports:
      - "8082:8080"
    volumes:
      - ./cfg/node2.toml:/etc/node.toml
    command: 
      - --addr=node2:8080
      - --data=/tmp
      - --beehive-cfg=/etc/node.toml
      - --max=1000000
      - --dim=512

  node3:
    image: deepfabric/beevector
    ports:
      - "8083:8080"
    volumes:
      - ./cfg/node3.toml:/etc/node.toml
    command: 
      - --wait=10
      - --addr=node3:8080
      - --data=/tmp
      - --beehive-cfg=/etc/node.toml
      - --max=1000000
      - --dim=512
