FROM centos:7
RUN yum -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm && yum clean all && rm -rf /var/cache/yum
RUN yum -y install glog gflags openblas-devel jemalloc && yum clean all && rm -rf /var/cache/yum