# The beehive example configuration

# The node name in the cluster
name = "node1"

# The RPC address to serve requests
raftAddr = "node1:10001"

# The RPC address to serve requests
rpcAddr = "node1:10002"

maxConcurrencySnapChunks = 16
snapChunkSize = 8

applyWorkerCount = 16
raftMaxWorkers = 16

raftPreVote = true

# Raft tick time interval in ms.
raftTickDuration = 1000

# How many ticks to perform timeout elections.
raftElectionTick = 20

# How many ticks to perform raft headrtbeat.
raftHeartbeatTick = 2

raftThresholdCompactLog = 10

# Check the interval of shard split in seconds.
shardSplitCheckDuration = 5

maxProposalBytes = 32

[prophet]
# The application and prophet RPC address, send heartbeats, alloc id, watch event, etc. required
rpcAddr = "node1:9527"

# Store cluster metedata
storeMetadata = true

# The embed etcd client address, required while storeMetadata is true
clientAddr = "node1:2371"

# The embed etcd peer address, required while storeMetadata is true
peerAddr = "node1:2381"